name: PR Test

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: super-secret-ci-secret
      GITHUB_CLIENT_ID: a-github-client-id
      GITHUB_ACCESS_TOKEN: a-github-access-token
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_TOKEN }}
      DATABASE_URL: "mysql://root:root@localhost:3306/press?schema=public"
      SMTP_FROM: press@nicholasgriffin.dev
      RESEND_API_TOKEN: a-resend-api-token
      STRIPE_API_KEY: a-stripe-api-key
      STRIPE_WEBHOOK_SECRET: a-stripe-webhook-secret
      STRIPE_PRO_MONTHLY_PLAN_ID: a pro-plan-id

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.18.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
