name: "Welcome new contributors"

on: 
 issues: 
  types: opened
 pull_request:
   types: opened

permissions:
  pull-requests: write
  issues: write

jobs:
 welcome-message:
  name: Welcoming New Users
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: semantics
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Thank you for making your first Pull Request and taking the time to improve our package! Someone will be around to review it as soon as possible.
          issue-message: | 
            Thank you for opening your first issue, someone will get back to you as soon as possible.